/** TU ELEMENTO V3 CELL PREVIEW — fuente editorial canónica. */
(function(root){
'use strict';
root.TE_COPY_V3={
  estados:{
    prospero:{titulo:'Naciste con el viento a favor.',texto:'Lo que se te da bien aparece casi sin pensarlo. El trabajo está en notar cuándo esa facilidad ocupa demasiado espacio.'},
    fuerte:{titulo:'Traes buena base.',texto:'Tus cualidades salen con poca fricción. Conviene distinguir entre lo que te sale fácil y lo que realmente sirve en cada situación.'},
    debil:{titulo:'Lo tuyo está ahí, pero necesita condiciones.',texto:'Hay contextos donde esta parte de ti aparece con mucha más claridad. Esa diferencia te dice qué ambientes y apoyos te convienen.'},
    muerto:{titulo:'Te toca escoger mejor dónde gastas.',texto:'Tu energía cambia mucho según el contexto. Los lugares y personas que sí te sostienen hacen una diferencia visible.'},
    trampa:{titulo:'Tienes capacidad de sobra y aun así acabas agotado.',texto:'El desgaste viene de cómo usas esa capacidad. La misma herramienta puede ayudarte o vaciarte según la forma en que entres a la situación.'}
  },
  mezcla:{
    general:'Traes cinco ingredientes: Madera, Fuego, Tierra, Metal y Agua. Son cinco maneras distintas de resolver la vida. Casi nadie los tiene parejos: normalmente unas respuestas salen solas y otras piden más intención.',
    mas:'A esto le echas mano sin pensarlo. Es tu respuesta por default, y sale incluso cuando otra herramienta habría servido mejor.',
    menos:'Esto lo usas poco. Te cuesta arrancarlo y necesita más intención para salir. Se aprende usándolo en situaciones pequeñas y concretas.',
    intermedia:'Esto lo tienes disponible sin que se te suba al volante. Sale cuando la situación lo pide y después se retira.',
    balance:'Balancear tu carta significa dejar de pedirle a un solo ingrediente que te resuelva todo.'
  },
  elementos:{
    madera:{aporta:'Empezar, crecer, ir hacia algún lado.',mas:'Empiezas cinco cosas y todas te importan. Ninguna avanza como podría.',menos:'Sabes lo que quieres, pero el primer paso se te hace enorme.',probar:['Escoge una cosa y dale una semana completa.','Convierte una idea en un primer paso con fecha.','Revisa cuál proyecto ya creció suficiente y necesita otra etapa.']},
    fuego:{aporta:'Mostrarte, entusiasmar, hacer que se sienta que estás.',mas:'Andas encendido todo el tiempo y te vacías. Necesitas respuesta para saber que valió la pena.',menos:'Haces cosas buenas de las que casi nadie se entera.',probar:['Muestra una versión que ya se entienda.','Aparta ratos donde nadie te pida respuesta ni presencia.','Celebra avances concretos para que el impulso tenga cierre.']},
    tierra:{aporta:'Sostener, dar continuidad, ser el piso.',mas:'Sostienes cosas que ya se acabaron, nada más porque ya las sostenías.',menos:'Se te cae lo que empiezas por falta de rutina y continuidad.',probar:['Pon una rutina chiquita al servicio de algo que sí importa.','Conserva lo que funciona y mueve lo demás.','Termina una tarea antes de convertirla en un sistema entero.']},
    metal:{aporta:'Decidir, cortar, poner el punto final.',mas:'Decides antes de tener todos los datos y luego cuesta reabrir la decisión.',menos:'Todo sigue abierto. Ninguna conversación termina del todo.',probar:['Define dos o tres criterios antes de decidir.','Cierra ese pendiente que sigue ocupando espacio mental.','Pide una segunda opinión cuando una decisión te parezca demasiado obvia.']},
    agua:{aporta:'Conectar información, encontrar rutas, cambiar de plan.',mas:'Ves tantas opciones que ninguna se ve claramente mejor.',menos:'Te clavas en un solo camino aunque ya perdió sentido.',probar:['Ponle hora límite a la investigación antes de decidir.','Escoge una pregunta concreta.','Deja reposar una decisión y vuelve a ella con un criterio escrito.']}
  },
  formas:{
    Espejo:{titulo:'Decides por tu cuenta',area:'Vínculos',corto:'Tú decides. Consultar es opcional y muchas veces ya traes resuelto lo que sigue.',nota:'Te llevas con gente que se parece a ti. Te incomoda deber favores. En un grupo, tu primer reflejo es cuidar que sigues siendo tú.',costo:'Pides ayuda tarde, cuando el problema ya creció bastante.',prueba:'Cuéntale una decisión a alguien antes de cerrarla y observa qué mejora sin dejar de sentirse tuya.'},
    Contrapunto:{titulo:'Te defines contra',area:'Vínculos',corto:'El contraste te aclara. Con alguien enfrente te vuelves mucho más preciso con lo que quieres.',nota:'Comparas, negocias y mides el espacio que ocupas y el que ocupan los demás, aunque nadie más esté midiéndolo.',costo:'Tu rumbo puede acabar dependiendo demasiado de quién te tocó enfrente.',prueba:'Antes de compararte, escribe qué querías tú cuando todavía nadie más estaba en la ecuación.'},
    Flujo:{titulo:'Lo que traes adentro sale',area:'Expresión',corto:'Ideas, explicaciones, clases, productos. Lo que traes dentro busca salida rápido.',nota:'Haces, enseñas y produces. Cuando algo te prende, muchas veces ya empezaste antes de decidir formalmente que ibas a empezar.',costo:'Abres más frentes de los que alcanzas a cerrar y se te acumulan cosas al 80%.',prueba:'Termina una antes de darle toda tu atención a la siguiente idea.'},
    Impacto:{titulo:'Mueves el avispero',area:'Expresión',corto:'Ves cómo debería ser algo y te cuesta quedarte callado cuando sabes que puede cambiar.',nota:'Detectas lo que está mal hecho antes que nadie y provocas reacción, a veces con intención y a veces de rebote.',costo:'La intensidad puede convertir una mejora en pleito y el pleito termina comiéndose la mejora.',prueba:'Separa el cambio que quieres lograr de la reacción que quieres provocar.'},
    Oportunidad:{titulo:'Ves puertas',area:'Recursos',corto:'Detectas movimiento antes que otros. Intercambios, contactos y chances entran rápido en tu radar.',nota:'Sueles traer varias opciones a la vez y disfrutas compararlas.',costo:'Una puerta nueva puede verse mejor porque todavía no te ha enseñado su costo.',prueba:'Ponle fecha, precio y siguiente paso a una oportunidad antes de llamarla oportunidad.'},
    Concreción:{titulo:'Necesitas que se pueda tocar',area:'Recursos',corto:'Necesitas que el esfuerzo termine convertido en algo real: números, resultados, cosas terminadas.',nota:'Ordenas recursos, mides y construyes despacio, pero lo que construyes suele quedarse.',costo:'Asegurar cada variable puede hacer que el momento se mueva antes que tú.',prueba:'Define qué significa suficientemente resuelto antes de seguir optimizando.'},
    Desafío:{titulo:'Te enciendes bajo presión',area:'Estructura',corto:'Cuando las cosas se ponen feas, tu cabeza se aclara y aparece una parte muy resolutiva.',nota:'Urgencias, competencia y problemas concretos te empujan a decidir rápido.',costo:'Puedes acostumbrarte al modo emergencia y tratar un martes como si fuera una crisis.',prueba:'Haz una parte importante antes de que se vuelva urgente y compara cómo cambia tu decisión.'},
    Estructura:{titulo:'Necesitas saber qué te toca',area:'Estructura',corto:'Con roles y reglas claras te mueves con menos desgaste; en el desorden gastas el doble.',nota:'Cumples, llegas y sostienes acuerdos incluso cuando nadie está revisando.',costo:'Puedes seguir cumpliendo reglas que ya dejaron de servirte solo porque siguen siendo las reglas.',prueba:'Escoge una responsabilidad actual y define qué resultado concreto debería producir. Si ya dejó de producirlo, renegóciala.'},
    Intuición:{titulo:'Llegas por otro lado',area:'Perspectiva',corto:'Aprendes en zigzag. Conectas cosas que venían separadas y llegas a respuestas por rutas poco obvias.',nota:'Te salen corazonadas útiles, soluciones raras e interés por temas que otros pasan de largo.',costo:'Encontrar conexiones en todo complica decidir cuál merece convertirse en acción.',prueba:'Después de una corazonada, busca un dato pequeño que pueda confirmarla o tumbarla.'},
    Aprendizaje:{titulo:'Necesitas entender primero',area:'Perspectiva',corto:'El conocimiento te da piso. Cuando entiendes cómo funciona algo, te sueltas.',nota:'Estudias antes de moverte, buscas referencias y le preguntas a quien sabe.',costo:'Prepararte puede convertirse en una forma elegante de posponer la prueba real.',prueba:'Convierte lo último que aprendiste en una acción visible esta semana.'}
  }
};
})(typeof globalThis!=='undefined'?globalThis:this);
